CREATE TABLE `leads` (
	`id` text PRIMARY KEY NOT NULL,
	`created_at` text DEFAULT CURRENT_TIMESTAMP NOT NULL,
	`source_url` text DEFAULT '' NOT NULL,
	`user_agent` text DEFAULT '' NOT NULL,
	`contact_name` text NOT NULL,
	`contact_method` text NOT NULL,
	`contact_region` text DEFAULT '' NOT NULL,
	`contact_message` text DEFAULT '' NOT NULL,
	`vat_amount` text DEFAULT '' NOT NULL,
	`people_count` integer DEFAULT 0 NOT NULL,
	`min_wage` text DEFAULT '' NOT NULL,
	`avg_wage` text DEFAULT '' NOT NULL,
	`salary` text DEFAULT '' NOT NULL,
	`social` text DEFAULT '' NOT NULL,
	`tax_rate` text DEFAULT '' NOT NULL,
	`business` text DEFAULT '' NOT NULL,
	`revenue` text DEFAULT '' NOT NULL,
	`separate` text DEFAULT '' NOT NULL,
	`employment` text DEFAULT '' NOT NULL,
	`grade` text DEFAULT '' NOT NULL,
	`hires` integer DEFAULT 0 NOT NULL,
	`ratio` text DEFAULT '' NOT NULL,
	`vat_potential` text DEFAULT '' NOT NULL,
	`fund_potential` text DEFAULT '' NOT NULL,
	`income_tax_potential` text DEFAULT '' NOT NULL,
	`total_benefit` text DEFAULT '' NOT NULL,
	`annual_cost` text DEFAULT '' NOT NULL,
	`net_benefit` text DEFAULT '' NOT NULL,
	`eligible` integer DEFAULT false NOT NULL,
	`issues` text DEFAULT '' NOT NULL,
	`lead_text` text DEFAULT '' NOT NULL,
	`raw_payload` text DEFAULT '' NOT NULL
);
